#+options: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+options: author:t broken-links:mark c:nil creator:nil
#+options: d:(not "LOGBOOK") date:t e:t email:nil expand-links:t f:t
#+options: inline:t num:nil p:nil pri:nil prop:nil stat:t tags:t
#+options: tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+language: en
#+select_tags: export
#+exclude_tags: noexport
#+creator: Emacs 31.0.50 (Org mode 9.7.14)

# #+odt_preferred_output_format: pdf
#+title: Test drive the enhanced ox-odt package in a sandboxed environment
#+subtitle: Emacs 31.0.50 (Org mode 9.7.14)

#+ATTR_ODT: :style "OrgSubtitle"
#+begin_center
Export to ODT (and DOCX) with CSL citations

Export to ODS (and XLSX)
#+end_center

* Create a sandbox directory (= =~/tmp/sandbox-for-ox-odt/=)

- Create a temporary directory called =~/tmp/sandbox-for-ox-odt/=

- Create an =init.el= in the above directory with the contents you see
  below.

  The =init.el= file does the following

  - Adds =ox-odt= ELPA to =package-archives=

  - Configures Emacs so that it uses
    =~/tmp/sandbox-for-ox-odt/package-el= as the directory where =ox-odt=
    and its dependencies (= =org=, =peg=, =citeproc=, =rnc-mode=,
    =seq=) are installed

  - Installs the =ox-odt= package.

  #+caption: Custom =init.el=  
  #+begin_src emacs-lisp :exports code :results none
    ;;;; init --- Init file for test driving ox-odt package in a sandbox environment -*- lexical-binding: t; coding: utf-8-emacs; -*-
    ;;; Commentary:

    ;; Put this file under "~/tmp/sandbox-for-ox-odt/" and Emacs with
    ;;
    ;;     emacs -Q --init-directory=~/tmp/sandbox-for-ox-odt/ -l ~/tmp/sandbox-for-ox-odt/init.el
    ;;
    ;; This init file automatically installs `ox-odt' from
    ;; https://kjambunathan.github.io/elpa/ in the above sandbox
    ;; directory.
    ;;
    ;; Once `ox-odt' is installed you will be dropped in to an `org'
    ;; buffer named `test-drive-ox-odt.org'. You can try exporting this
    ;; file to /*both*/ LibreOffice Writer / ODT (with `C-c C-e o O') and
    ;; ODS / LibreOffice Calc (with `C-c C-e o S').
    ;;
    ;; If all goes well, then you have succesfully installed a ox-odt
    ;; package in a custom environment.

    ;;; Code:

    (defvar org-mode-ox-odt-sandbox-root
      (expand-file-name "~/tmp/sandbox-for-ox-odt/")
      "Sanbox directory / Init directory for testing ox-odt package.")

    (defvar org-mode-ox-odt-sandbox-elpa
      (expand-file-name "package-el" org-mode-ox-odt-sandbox-root)
      "Sub-directory under the sandbox directory where ox-odt's pre-requisites are installed.")

    ;; Create the above directory
    (make-directory org-mode-ox-odt-sandbox-elpa  'parents)

    ;; Configure Emacs Package Manager
    (custom-set-variables
     ;; Install ox-odt & its pre-requisites in the sandbox directory.
     '(package-user-dir org-mode-ox-odt-sandbox-elpa)
     ;; The packages come from sandbox directory alone and not from elsewhere.
     '(package-directory-list (list org-mode-ox-odt-sandbox-elpa))
     ;; Set up ELPA repos
     '(package-archives
       '(("gnu-devel" . "https://elpa.gnu.org/devel/")
         ("gnu" . "https://elpa.gnu.org/packages/")
         ("nongnu" . "https://elpa.nongnu.org/nongnu/")
         ("melpa" . "https://melpa.org/packages/")
         ("ox-odt" . "https://kjambunathan.github.io/elpa/")))
     ;; If a package is available from multiple ELPAs, prefer ELPAs
     ;; maintained by gnu.org, melpa.org and ox-odt in that order.
       '(package-archive-priorities
        '(("gnu" . 100)
          ("nongnu" . 90)
          ("gnu-devel" . 80)
          ("melpa" . 70)
          ("ox-odt" . 60))))

    ;; Initialize the Emacs Package Manager, install ox-odt and all its
    ;; dependencies under the sandbox directory.
    (package-initialize)
    (package-refresh-contents)
    (package-install 'ox-odt)
    (package-upgrade-all)

    ;; Load ODS and ODT exporters.  Load `citeproc' so that ODT exporter
    ;; uses custom styles for Citations and Bibliographies.
    (require 'citeproc)
    (require 'ox-odt)
    (require 'ox-ods)

    ;; Offer the User a sample `org' file for test driving.
    (find-file (expand-file-name "./test-drive-ox-odt/test-drive-ox-odt.org"
                                 org-mode-ox-odt-sandbox-root))
  #+end_src

* Start a /minimal/ Emacs that uses /the enhanced =ox-odt=/

- Start Emacs with the command you see below.

  Note that

  - Emacs is started with the =-Q= flag.

    This ensures that you run a pristine Emacs with /none/ of your own
    customizations.

  - Emacs uses =~/tmp/sandbox-for-ox-odt/= as its =init-directory=

  - Emacs uses a minimal =init.el= described above.

  #+begin_src sh
    emacs -Q --init-directory=~/tmp/sandbox-for-ox-odt/ -l ~/tmp/sandbox-for-ox-odt/init.el
  #+end_src

  In other words, you start an Emacs session that runs the latest
  version of =ox-odt= and the latest version of all its
  pre-requisites.

* Test drive some =org= files  

Visit an =org= file, say,
=~/tmp/sandbox-ox-odt/test-drive-ox-odt/test-drive-ox-odt.org=, and

  - Export to =odt= with =C-c C-e o O= or
  - Export to =ods= with =C-c C-e o S=

In addition to the above mentioned =org= file, you can use any of
the =org= files under the =~/tmp/sandbox-for-ox-odt/= directory.

If the latest version of =ox-odt= is =9.7.14.644= then the =org=
files available for you to test drive are given below.

#+begin_example
  kjambunathan@debian-ng:~/tmp/sandbox-for-ox-odt$ find . -name '*.org'

  ./package-el/ox-odt-9.7.14.644/samples/subdocument1.org
  ./package-el/ox-odt-9.7.14.644/samples/tblfms-to-ods.org
  ./package-el/ox-odt-9.7.14.644/samples/pagebreak.org
  ./package-el/ox-odt-9.7.14.644/samples/masterdocument.org
  ./package-el/ox-odt-9.7.14.644/samples/citeproc/citeproc-contents.org
  ./package-el/ox-odt-9.7.14.644/samples/citeproc/citeproc-multi.org
  ./package-el/ox-odt-9.7.14.644/samples/citeproc/citeproc.org
  ./Test drive the enhanced ox-odt package in a sanboxed environment.org
  ./test-drive-ox-odt/test-drive-ox-odt.org
#+end_example

